name: Build README
on:
  schedule:
    - cron: '0 0 * * *' # at 00:00 everyday
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/build-script/requirements.txt
    - name: Update README
      run: |-
        python .github/build-script/create_readme.py
        cat README.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Commit changes
      run: |
        git config user.name "fiboa CI"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m ":robot: Automated update README: ${timestamp} [skip ci]" || exit 0
        git push